controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    head_controller:
      type: position_controllers/JointGroupPositionController

# Parámetros específicos del controlador (Jazzy)
head_controller:
  ros__parameters:
    joints: [neck_yaw, neck_pitch, head_roll]
